apiVersion: apps/v1
kind: Deployment
metadata:
  name: composite-app
spec:
  selector:
    matchLabels:
      app: composite-app
  replicas: 1
  template:
    metadata:
      labels:
        app: composite-app
    spec:
      containers:
        - name: composite-app
          image: abhishekjv/composite-service:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: composite-app-service
spec:
  selector:
    app: composite-app
  ports:
    - name: http
      port: 8080
      nodePort: 30082
  type: NodePort
---

