apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingress-gateway-configuration
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
    - port:
        number: 8080
        name: http
        protocol: HTTP
      hosts:
        - "*" # Domain name of the external website
---
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: product-service-routing-rules # "just" a name for this virtualservice
  namespace: default
spec:
  hosts:
    - "*"
  gateways:
    - ingress-gateway-configuration
  http:
    - route:
        - destination:
            host: product-service.default.svc.cluster.local # The Target DNS name
            subset: safe-group # The name defined in the DestinationRule
          weight: 50
        - destination:
            host: product-service.default.svc.cluster.local # The Target DNS name
            subset: risky-group # The name defined in the DestinationRule
          weight: 50
---
kind: DestinationRule # Defining which pods should be part of each subset
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: product-service-canary-release-dr # This can be anything you like.
  namespace: default
spec:
  host: product-service # Service
  #trafficPolicy: ~
  subsets:
    - labels: # SELECTOR.
        version: stable # find pods with label "safe"
      name: safe-group
    - labels:
        version: new
      name: risky-group
